#!/usr/bin/env bash
# test-protection-data-driven.sh — verify the protection stack is fully data-driven.
#
# Asserts that load-shedder.nix, tier1-apps.nix, watchdog.nix and health-agent.nix
# read their thresholds / tier-1 lists from the consolidated cloud-data
# (config.json native.protection defaults + b_infra/nixhm-sudo-<alias>/build.json
# .protection per-VM overrides) — NOT from hardcoded Nix literals — by evaluating
# each module with a real vmName and grepping the generated script/unit text for
# the expected data-driven values.
#
# Covers PLAN-hardening-2026-07-07 §1B P1-P5 + §3B/§3C.
#
# Run:  bash test-protection-data-driven.sh
# Deps: nix-instantiate (pure eval, no build — safe on any machine incl. termux).
#
# PART 1 is a SYNTAX + DATA-FLOW test.
# PART 2 drives the shedder's UN-SHED path for real against stubbed docker /
# systemctl. It is here rather than in the stress harness because the un-shed
# path is not a pressure behaviour: it is pure shell control flow over a list
# persisted in /run, so it needs a fake docker and a scripted PSI sequence, not
# a thrashing box. The trigger side (does memory pressure actually shed?) stays
# in the stress-ng GHA harness spec in test-tier1-stress.md — never run that here.
set -euo pipefail

MODULES_DIR="$(cd "$(dirname "$0")/.." && pwd)"   # .../src/modules
cd "$MODULES_DIR"

command -v nix-instantiate >/dev/null 2>&1 || {
  echo "SKIP: nix-instantiate not available"; exit 0
}

TEST_NIX="$(mktemp --suffix=.nix -p "$MODULES_DIR")"
RENDER_NIX="$(mktemp --suffix=.nix -p "$MODULES_DIR")"
WORK="$(mktemp -d)"
trap 'rm -f "$TEST_NIX" "$RENDER_NIX"; rm -rf "$WORK"' EXIT

cat > "$TEST_NIX" <<'EOF'
let
  lib = import <nixpkgs/lib>;
  pkgs = { gawk = "/gawk-stub"; systemd = "/systemd-stub"; };
  config = {};
  ls = import ./protection/load-shedder.nix { inherit config pkgs lib; ramMB = 1024; vmName = "oci-mail"; };
  t1raw = import ./protection/tier1-apps.nix { inherit config pkgs lib; vmName = "gcp-proxy"; };
  t1emptyRaw = import ./protection/tier1-apps.nix { inherit config pkgs lib; vmName = "oci-apps"; };
  ha = import ./agents/health-agent.nix { inherit config pkgs lib; vmName = "oci-apps"; };
  wd = import ./protection/watchdog.nix { inherit config pkgs lib; ramMB = 1024; vmName = "oci-mail"; };
  t1 = t1raw.content;
  lsText = ls.home.file.".local/share/system-protection/load-shedder.sh".text;
  haText = ha.home.file.".local/share/system-protection/health-agent.sh".text;
  wdText = wd.home.file.".local/share/system-protection/watchdog-petter.service".text;
  # Read the per-VM source of truth directly, NOT the consolidated snapshot: the
  # consolidation is regenerated by the ship pipeline, so asserting a knob is
  # *declared* has to look at the file a human edits.
  ociApps = builtins.fromJSON (builtins.readFile ../../../../nixhm-sudo-oci-apps/build.json);
  has = lib.hasInfix;
in {
  # ── §3C graduated shed + P4 per-VM override (oci-mail warn=30) ──────────
  ls_tier1_maddy   = has ''TIER1_SERVICES="maddy stalwart mail-puller"'' lsText;
  ls_warn_override = has "MEM_PSI_WARN=30" lsText;   # per-VM override wins over default 35
  ls_page_default  = has "MEM_PSI_PAGE=65" lsText;
  # ── §3B tier1 slice reserved memory (gcp-proxy: 5 svc × 48MB = 240M) ────
  t1_gcp_on        = t1raw.condition;               # gcp-proxy has tier1 → module active
  t1_apps_off      = ! t1emptyRaw.condition;        # oci-apps no tier1 → mkIf false
  t1_slice_reserve = has "MemoryMin=240M" (t1.home.file.".local/share/system-protection/tier1.slice".text);
  t1_caddy_list    = has ''TIER1="caddy introspect-proxy authelia hickory-dns wireguard-mesh-ws-tunnel"''
                       (t1.home.file.".local/share/system-protection/tier1-watchdog.sh".text);
  # ── P2 fd thresholds + P3 wg-stale (defaults) ───────────────────────────
  ha_fd_warn       = has "FD_WARN_PCT=70" haText;
  ha_fd_crit       = has "FD_CRIT_PCT=90" haText;
  ha_wg_stale      = has "WG_STALE_SECS=180" haText;
  # ── P4 watchdog disk/docker/lowmem env injection ────────────────────────
  wd_disk_warn     = has "DISK_WARN=80" wdText;
  wd_docker_fail   = has "DOCKER_FAIL_THRESHOLD=120" wdText;
  wd_lowmem_prune  = has "LOW_MEM_PRUNE_MB=50" wdText;
  # ── un-shed: the crit shed must have an inverse, and it must be paced ────
  # The shed list is what makes the shed reversible; without it the recovery
  # edge can only restart docker, which is how ~40 containers stayed stopped on
  # an idle box (2026-09-09). These assert the wiring exists at all — PART 2
  # asserts it behaves.
  ls_shed_list     = has "/run/load-shedder.shed-list" lsText;
  ls_unshed_shot   = has "UNSHED: single-shot start of shed containers" lsText;
  ls_unshed_latch  = has "UNSHED FAILED" lsText;
  # The pacing knob is DECLARED per-VM on the box with the longest restore
  # queue, not silently inherited: a default nobody can see is a default nobody
  # retunes when the container count doubles.
  ls_unshed_declared = ociApps.protection ? unshed_delay_secs;
}
EOF

echo "== PART 1: evaluating protection modules with real vmName =="
RESULT="$(nix-instantiate --eval --strict --json "$TEST_NIX")"
echo "$RESULT" | tr ',' '\n' | sed 's/[{}"]//g'

# Fail if any assertion is false.
if echo "$RESULT" | grep -q ':false'; then
  echo "FAIL: one or more data-driven assertions were false (see above)"
  exit 1
fi
echo "PASS: all protection thresholds + tier-1 lists are data-driven from consolidated cloud-data"

# ═══════════════════════════════════════════════════════════════════════════
# PART 2 — runtime: drive crit → clear and prove the shed has an inverse.
# ═══════════════════════════════════════════════════════════════════════════
# The shed list path is a literal /run/load-shedder.shed-list inside the
# shedder, so this section needs a writable /run. It is gated rather than
# redirected because rewriting the script to test it would test a script that
# is not the one we ship.
echo
echo "== PART 2: un-shed path (stubbed docker, scripted PSI) =="

SHED_LIST=/run/load-shedder.shed-list
FIRED=/run/load-shedder.fired

# Never race a real shedder: it owns these files and this test truncates them.
if [ -e "$SHED_LIST" ] || systemctl is-active --quiet load-shedder.service 2>/dev/null; then
  echo "SKIP(runtime): a live load-shedder owns /run/load-shedder.* on this host"
  exit 0
fi
if ! ( : > "$SHED_LIST" ) 2>/dev/null; then
  echo "SKIP(runtime): /run is not writable — re-run as root to exercise the un-shed loop"
  exit 0
fi
rm -f "$SHED_LIST"

cat > "$RENDER_NIX" <<'EOF'
let lib = import <nixpkgs/lib>;
in (import ./protection/load-shedder.nix {
     config = {}; pkgs = {}; inherit lib; ramMB = 1024; vmName = "oci-apps";
   }).home.file.".local/share/system-protection/load-shedder.sh".text
EOF

SHEDDER="$WORK/load-shedder.sh"
nix-instantiate --eval --strict --raw "$RENDER_NIX" > "$SHEDDER"

# Tier-1 comes from the rendered script, not from a copy of the JSON in this
# test: duplicating the list here would make the test pass while the shipped
# script protects something else.
TIER1="$(sed -n 's/^TIER1_SERVICES="\([^"]*\)".*/\1/p' "$SHEDDER" | head -1)"
[ -n "$TIER1" ] || { echo "FAIL: no TIER1_SERVICES in rendered script"; exit 1; }
# Sheddable fixtures. ntfy-exporter shares a prefix with tier-1 "ntfy" on
# purpose: a prefix match instead of an equality match would wrongly protect it.
SHEDDABLE="my-ai-api agent-runner-1 ntfy-exporter agent-runner-2 umami"
echo "   tier1 (from rendered script): $TIER1"
echo "   sheddable fixtures:           $SHEDDABLE"

AWK_REAL="$(command -v awk)"
FAILED=0

assert() { # $1 = description, $2... = predicate command
  local desc="$1"; shift
  if "$@"; then echo "  ok   $desc"; else echo "  FAIL $desc"; FAILED=$((FAILED + 1)); fi
}

# Scenario builder. $1 = name, $2 = newline PSI sequence, $3 = names whose
# `docker start` must fail. Leaves everything it recorded under $SCEN.
run_scenario() {
  SCEN="$WORK/$1"
  mkdir -p "$SCEN/bin"
  printf '%s\n' $2 > "$SCEN/psi-seq"
  printf '%s\n' ${3:-} | grep -v '^$' > "$SCEN/start-fails" || true
  echo 1 > "$SCEN/psi-cursor"
  : > "$SCEN/log"; : > "$SCEN/docker-calls"; : > "$SCEN/starts"
  : > "$SCEN/timeline"; : > "$SCEN/ntfy"; : > "$SCEN/systemctl-calls"
  printf '%s\n' $TIER1 $SHEDDABLE | sort > "$SCEN/running"
  rm -f "$SHED_LIST" "$FIRED"

  mk_stub() { # $1 = command name; body on stdin. Paths baked, not inherited:
              # the stubs must work regardless of how the shedder is invoked.
    { echo '#!/bin/sh'; echo "SCEN='$SCEN'"; echo "AWK_REAL='$AWK_REAL'"; cat; } > "$SCEN/bin/$1"
    chmod +x "$SCEN/bin/$1"
  }

  # The shedder reads PSI only through `awk ... /proc/pressure/<kind>`, so that
  # is the seam for feeding pressure. Every other awk call (the docker-stats
  # ordering in shed_non_tier1) is delegated to the real one — stubbing it
  # wholesale would silently change the code path under test.
  mk_stub awk <<'STUB'
case " $* " in
  *"/proc/pressure/memory"*)
    n=$(cat "$SCEN/psi-cursor")
    v=$(sed -n "${n}p" "$SCEN/psi-seq")
    if [ -z "$v" ]; then : > "$SCEN/psi-exhausted"; echo 0
    else echo $((n + 1)) > "$SCEN/psi-cursor"; echo "$v"; fi ;;
  *"/proc/pressure/"*) echo 0 ;;   # cpu/io are logged, never shed on
  *) exec "$AWK_REAL" "$@" ;;
esac
STUB

  # The shedder loops forever by design, so the scenario ends when the scripted
  # pressure runs out: SIGTERM the shell that called us. A wall-clock timeout
  # would make the assertions depend on how fast the box is.
  mk_stub sleep <<'STUB'
echo "sleep:$1" >> "$SCEN/timeline"
if [ -e "$SCEN/psi-exhausted" ]; then kill -TERM "$PPID" 2>/dev/null; fi
exit 0
STUB

  mk_stub docker <<'STUB'
echo "$*" >> "$SCEN/docker-calls"
cmd="$1"; shift
case "$cmd" in
  ps) cat "$SCEN/running" ;;
  # `docker stats` is timeout-guarded in shed_non_tier1 because it is unreliable
  # under thrash; fail it so the `docker ps` fallback is what gets exercised.
  stats) exit 1 ;;
  stop)
    # Snapshot the persisted list at the instant the shed happens — the shedder
    # deletes it on a successful un-shed, and it is the thing under test.
    cat /run/load-shedder.shed-list >> "$SCEN/shed-list-snapshot" 2>/dev/null || true
    for c in "$@"; do
      grep -vxF "$c" "$SCEN/running" > "$SCEN/running.tmp" || true
      mv "$SCEN/running.tmp" "$SCEN/running"
    done ;;
  start)
    for c in "$@"; do
      echo "$c" >> "$SCEN/starts"
      echo "start:$c" >> "$SCEN/timeline"
      grep -qxF "$c" "$SCEN/start-fails" 2>/dev/null && exit 1
      echo "$c" >> "$SCEN/running"
    done ;;
esac
exit 0
STUB

  # docker.service stays up throughout: these scenarios are the shed_level=1
  # container un-shed, not the full-shed daemon restart.
  mk_stub systemctl <<'STUB'
echo "$*" >> "$SCEN/systemctl-calls"
exit 0
STUB

  mk_stub logger <<'STUB'
echo "$*" >> "$SCEN/log"
exit 0
STUB

  # Succeed so the shedder takes its normal notify path; the bodies are evidence.
  mk_stub curl <<'STUB'
echo "$*" >> "$SCEN/ntfy"
exit 0
STUB

  # 60s is a deadlock backstop, not the exit condition — the sleep stub is.
  # The group redirect silences the shell's own "Terminated" notice for the
  # SIGTERM we asked for; a stray "Terminated" in the middle of passing
  # assertions reads like a failure. A subshell would not work here: bash execs
  # it into timeout, leaving no shell inside to redirect.
  { timeout 60 env PATH="$SCEN/bin:$PATH" sh "$SHEDDER" >/dev/null 2>&1 || true; } 2>/dev/null
}

log_has()  { grep -qF "$2" "$WORK/$1/log"; }
ntfy_has() { grep -qF "$2" "$WORK/$1/ntfy"; }
# Same multiset of names, order-independent.
same_set() { [ "$(sort "$1" | tr -d ' ')" = "$(printf '%s\n' $2 | sort | tr -d ' ')" ]; }
count_lines() { [ "$(wc -l < "$1")" -eq "$2" ]; }
count_calls() { [ "$(grep -c "^$3" "$WORK/$1/docker-calls")" -eq "$2" ]; }
# Pacing: the shedder must pause between each start, so every start line in the
# timeline is immediately followed by a sleep line.
starts_are_paced() { awk '/^start:/ { if ((getline nxt) <= 0 || nxt !~ /^sleep:/) { bad = 1 } } END { exit bad }' "$WORK/$1/timeline"; }
unshed_delay_used() { awk '/^start:/ { if ((getline nxt) > 0) { sub(/^sleep:/, "", nxt); print nxt } }' "$WORK/$1/timeline" | sort -u; }
# Exact-token match, not grep -w: "-" is a word boundary, so -w would let a
# stopped ntfy-exporter satisfy an assertion about tier-1 ntfy.
never_touched() { ! tr ' ' '\n' < "$WORK/$1/docker-calls" | grep -qxF "$2"; }

# ── A: pressure clears, every shed container comes back ───────────────────
# Three crit ticks (>= crit, < page) reach NEED, then a clear tick fires the
# recovery edge; a trailing tick exhausts the sequence and ends the run.
echo "-- scenario A: crit shed -> pressure clears -> full un-shed"
run_scenario A "55 55 55 0 0" ""

assert "shed list persisted exactly the non-tier1 containers" \
  same_set "$WORK/A/shed-list-snapshot" "$SHEDDABLE"
assert "every name in the shed list got a docker start" \
  same_set "$WORK/A/starts" "$SHEDDABLE"
assert "no container was started twice" \
  count_lines "$WORK/A/starts" "$(printf '%s\n' $SHEDDABLE | wc -l)"
for t in $TIER1; do
  assert "tier-1 $t was never stopped or started" never_touched A "$t"
done
assert "starts are paced one-by-one (start always followed by a sleep)" starts_are_paced A
assert "un-shed reported success" log_has A "UNSHED: all shed containers restarted"
assert "recovery was notified loudly" ntfy_has A "RECOVERY — shed containers restarted"
assert "shed list cleared after a clean un-shed" test ! -e "$SHED_LIST"
assert "fired marker cleared after a clean un-shed" test ! -e "$FIRED"
echo "   unshed pause between starts (secs): $(unshed_delay_used A | tr '\n' ' ')"

# ── B: one container refuses to start — latch, do not retry ───────────────
# Two full crit->clear cycles. The second cycle is what makes the latch
# assertion non-vacuous: the shedder gets a second recovery edge and must
# still not touch docker start.
echo "-- scenario B: failed restart latches off instead of retrying"
run_scenario B "55 55 55 0 55 55 55 0 0" "agent-runner-1"

assert "the second crit cycle really did shed again" count_calls B 2 "stop "
assert "each container was attempted exactly once across BOTH cycles" \
  count_lines "$WORK/B/starts" "$(printf '%s\n' $SHEDDABLE | wc -l)"
assert "the first cycle attempted every shed name" \
  same_set "$WORK/B/starts" "$SHEDDABLE"
assert "failure was reported, not swallowed" log_has B "UNSHED FAILED: still down: agent-runner-1"
assert "failure paged" ntfy_has B "UNSHED FAILED — containers still down"
assert "second recovery edge refused to retry" log_has B "already attempted and failed — not retrying"
assert "shed list kept for the human after a failed un-shed" test -e "$SHED_LIST"

rm -f "$SHED_LIST" "$FIRED"

if [ "$FAILED" -ne 0 ]; then
  echo "FAIL: $FAILED runtime assertion(s) failed — the shed has no working inverse"
  exit 1
fi
echo "PASS: crit shed is reversible, paced, and latches off on a failed restart"
