# Deploys dnsmasq as a Docker container on the `infra` network.
# Provides container-name DNS resolution for all containers on the VM.
#
# Without this, Docker's embedded DNS (127.0.0.11) does not work when
# the Docker daemon runs with iptables:false — this replaces it.
#
# Architecture:
#   - Runs as a container at a fixed IP (always .2 in the VM subnet)
#   - Mounts /etc/dnsmasq.d (written by this module) read-only
#   - All other containers set dns: [dnsIp]
#   - Upstream: Cloudflare + Google
#
# Usage in VM config:
#   (import ./modules/dnsmasq.nix {
#     vmName   = "gcp-proxy";
#     dnsIp    = "172.20.0.2";
#     subnet   = "172.20.0.0/24";
#     containers = {
#       caddy             = "172.20.0.10";
#       authelia          = "172.20.0.11";
#       "introspect-proxy" = "172.20.0.12";
#     };
#     meshPeers = {
#       "oci-apps"      = "10.0.0.6";
#       "oci-mail"      = "10.0.0.3";
#       "oci-analytics" = "10.0.0.4";
#     };
#   })

{ vmName, dnsIp, subnet, containers ? {}, meshPeers ? {} }:

{ config, lib, pkgs, ... }:

let
  containerRecords = builtins.concatStringsSep "\n" (
    builtins.attrValues (builtins.mapAttrs (name: ip:
      "host-record=${name},${ip}"
    ) containers)
  );

  meshRecords = builtins.concatStringsSep "\n" (
    builtins.attrValues (builtins.mapAttrs (name: ip:
      "host-record=${name},${ip}\nhost-record=${name}.internal,${ip}"
    ) meshPeers)
  );

  # Dnsmasq config files (written to /etc/dnsmasq.d/ by activation)
  containersConf = ''
    # Container host records for ${vmName}
    # Generated by home-manager dnsmasq.nix — do not edit manually
    ${containerRecords}
  '';

  meshConf = ''
    # WireGuard mesh peer records
    # Generated by home-manager dnsmasq.nix — do not edit manually
    ${meshRecords}
  '';

  upstreamConf = ''
    # Upstream DNS forwarding
    server=1.1.1.1
    server=1.0.0.1
    server=8.8.8.8
    cache-size=1000
    neg-ttl=60
    min-cache-ttl=300
  '';

  # Alpine-based Dockerfile (multi-arch: amd64 + arm64)
  dockerfile = ''
    FROM alpine:3.19
    RUN apk add --no-cache dnsmasq
    EXPOSE 53/udp 53/tcp
    CMD ["dnsmasq", "--no-daemon", "--conf-dir=/etc/dnsmasq.d", "--log-facility=-"]
  '';

  # Docker Compose for the dnsmasq container
  dockerCompose = ''
    # DO NOT EDIT — generated by home-manager dnsmasq.nix (${vmName})
    services:
      dnsmasq:
        build: .
        image: dnsmasq-local:latest
        container_name: dnsmasq
        restart: unless-stopped
        cap_add:
          - NET_ADMIN
          - NET_RAW
        volumes:
          - /etc/dnsmasq.d:/etc/dnsmasq.d:ro
        ports:
          - "127.0.0.1:53:53/udp"
          - "127.0.0.1:53:53/tcp"
        networks:
          infra:
            ipv4_address: ${dnsIp}
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "3"
        security_opt:
          - no-new-privileges:true
        stop_grace_period: 10s

    networks:
      infra:
        external: true
  '';

in {
  home.activation.dnsmasqDeploy = lib.hm.dag.entryAfter ["dockerNetwork"] ''
    (
    trap 'echo "[dnsmasq] FAILED at line $LINENO: $BASH_COMMAND" >&2' ERR

    SUDO=""
    for p in /usr/bin/sudo /run/wrappers/bin/sudo /usr/local/bin/sudo; do
      [ -x "$p" ] && SUDO="$p" && break
    done
    if [ -z "$SUDO" ]; then
      echo "[dnsmasq] WARNING: sudo not found — skipping"
      exit 0
    fi

    # Ensure Docker is running
    if ! docker info >/dev/null 2>&1; then
      echo "[dnsmasq] WARNING: Docker not available — skipping"
      exit 0
    fi

    # Write /etc/dnsmasq.d config files
    $SUDO mkdir -p /etc/dnsmasq.d

    PREV_CONTAINERS=""
    if $SUDO test -f /etc/dnsmasq.d/containers.conf; then
      PREV_CONTAINERS=$($SUDO cat /etc/dnsmasq.d/containers.conf 2>/dev/null || true)
    fi
    NEW_CONTAINERS="${containersConf}"

    printf '%s\n' "${containersConf}" | $SUDO tee /etc/dnsmasq.d/containers.conf > /dev/null
    printf '%s\n' "${meshConf}" | $SUDO tee /etc/dnsmasq.d/mesh.conf > /dev/null
    printf '%s\n' "${upstreamConf}" | $SUDO tee /etc/dnsmasq.d/upstream.conf > /dev/null

    # Write Dockerfile and docker-compose.yml to /opt/containers/dnsmasq
    $SUDO mkdir -p /opt/containers/dnsmasq
    printf '%s\n' "${dockerfile}" | $SUDO tee /opt/containers/dnsmasq/Dockerfile > /dev/null
    printf '%s\n' "${dockerCompose}" | $SUDO tee /opt/containers/dnsmasq/docker-compose.yml > /dev/null

    # Build image if not present (or Dockerfile changed)
    if ! docker image inspect dnsmasq-local:latest >/dev/null 2>&1; then
      echo "[dnsmasq] Building dnsmasq image..."
      $SUDO docker compose -f /opt/containers/dnsmasq/docker-compose.yml build
    fi

    # Start or recreate dnsmasq container
    if docker ps --filter name=dnsmasq --filter status=running | grep -q dnsmasq; then
      if [ "$PREV_CONTAINERS" != "$NEW_CONTAINERS" ]; then
        echo "[dnsmasq] Config changed — restarting dnsmasq"
        $SUDO docker compose -f /opt/containers/dnsmasq/docker-compose.yml up -d --force-recreate
      else
        echo "[dnsmasq] Already running, config unchanged"
      fi
    else
      echo "[dnsmasq] Starting dnsmasq at ${dnsIp}"
      $SUDO docker compose -f /opt/containers/dnsmasq/docker-compose.yml up -d
    fi

    echo "[dnsmasq] dnsmasq running at ${dnsIp} for ${vmName}"
    ) || echo "[dnsmasq] FAILED — see errors above, activation continues"
  '';
}
