# Shared ~/.node_modules for cloud VMs — provides tsx, typescript, and all
# service npm deps via a single install. Containers access via bind mount:
#   ~/.nix-profile/bin → node
#   ~/.node_modules/node_modules/.bin → tsx, tsc, etc.
#
# Source of truth: cloud-data-deps.json (generated by C3 API, synced by Dagu).
# This activation reads that file at switch time, generates package.json,
# and runs npm install.
#
# Fallback: static package.json with minimal deps (tsx + typescript).
{ config, lib, pkgs, ... }:

let
  nodejs = pkgs.nodejs_22;
in {
  # Set NODE_PATH so all tools resolve from shared dir
  home.sessionVariables.NODE_PATH = "$HOME/.node_modules/node_modules";

  # Add .bin to PATH for CLI tools (tsx, tsc, etc.)
  home.sessionPath = [ "$HOME/.node_modules/node_modules/.bin" ];

  # Activation: merge deps from cloud-data, generate package.json, npm install
  home.activation.sharedNodeModules = lib.hm.dag.entryAfter ["linkGeneration"] ''
    NODE_MODULES="$HOME/.node_modules"
    PKG_JSON="$NODE_MODULES/package.json"
    LOCK="$NODE_MODULES/node_modules/.package-lock.json"
    mkdir -p "$NODE_MODULES"

    CLOUD_DEPS="$HOME/git/cloud-data/cloud-data-deps.json"

    # Ensure package.json is writable (may be read-only from previous generation)
    [ -f "$PKG_JSON" ] && chmod u+w "$PKG_JSON" 2>/dev/null || true

    # Generate package.json from cloud-data deps (or use minimal fallback)
    if [ -f "$CLOUD_DEPS" ]; then
      printf "[node-deps] Merging deps from cloud-data-deps.json...\n"
      PATH="${nodejs}/bin:$PATH" ${nodejs}/bin/node -e "
        const fs = require('fs');
        const deps = {}, devDeps = {};
        const take = (obj, target) => {
          for (const [k, v] of Object.entries(obj || {})) {
            if (!target[k] || v > target[k]) target[k] = v;
          }
        };
        try {
          const d = JSON.parse(fs.readFileSync('$CLOUD_DEPS', 'utf8'));
          take(d.node?.merged?.dependencies, deps);
          take(d.node?.merged?.devDependencies, devDeps);
        } catch (e) { console.error('WARN: ' + e.message); }
        // Ensure tsx + typescript are always present
        if (!deps['tsx'] && !devDeps['tsx']) devDeps['tsx'] = '^4.19.0';
        if (!deps['typescript'] && !devDeps['typescript']) devDeps['typescript'] = '^5.7.0';
        const sort = o => Object.fromEntries(Object.entries(o).sort(([a],[b]) => a.localeCompare(b)));
        const pkg = {
          name: 'vm-shared-node-modules',
          private: true,
          description: 'Auto-generated by node-deps.nix from cloud-data-deps.json',
          dependencies: sort(deps),
          devDependencies: sort(devDeps)
        };
        fs.writeFileSync('$PKG_JSON', JSON.stringify(pkg, null, 2) + '\n');
        const total = Object.keys(deps).length + Object.keys(devDeps).length;
        console.log('[node-deps] package.json: ' + total + ' packages merged');
      " || {
        printf "[node-deps] WARN: merge failed, using minimal fallback\n"
        cat > "$PKG_JSON" << 'FALLBACK'
{
  "name": "vm-shared-node-modules",
  "private": true,
  "devDependencies": {
    "tsx": "^4.19.0",
    "typescript": "^5.7.0"
  }
}
FALLBACK
      }
    else
      printf "[node-deps] No cloud-data-deps.json found, using minimal fallback\n"
      cat > "$PKG_JSON" << 'FALLBACK'
{
  "name": "vm-shared-node-modules",
  "private": true,
  "devDependencies": {
    "tsx": "^4.19.0",
    "typescript": "^5.7.0"
  }
}
FALLBACK
    fi

    # npm install if package.json is newer than lock
    if [ -f "$PKG_JSON" ]; then
      if [ ! -d "$NODE_MODULES/node_modules" ] || [ "$PKG_JSON" -nt "$LOCK" ]; then
        printf "[node-deps] npm install: ~/.node_modules/\n"
        PATH="${nodejs}/bin:$PATH" $DRY_RUN_CMD ${nodejs}/bin/npm install \
          --prefix "$NODE_MODULES" \
          --no-audit --no-fund --legacy-peer-deps || true
      else
        printf "[node-deps] ~/.node_modules/ is up to date\n"
      fi
    fi
  '';
}
