# SSH key deployment — reads from .secrets.d/ (multiline) or .secrets (single-line)
# and writes to ~/.ssh/ so containers mounting ~/.ssh can SSH out via WireGuard.
{ lib, ... }:

{
  home.activation.sshKeys = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    SK_LOG="[ssh-keys]"
    SECRETS="$HOME/.config/home-manager/.secrets"
    SECRETS_D="$HOME/.config/home-manager/.secrets.d"
    SSH_DIR="$HOME/.ssh"
    SOCKETS="$SSH_DIR/sockets"

    if [ ! -f "$SECRETS" ] && [ ! -d "$SECRETS_D" ]; then
      echo "$SK_LOG No .secrets or .secrets.d — skipping"
      exit 0
    fi

    mkdir -p "$SSH_DIR" "$SOCKETS"
    chmod 700 "$SSH_DIR"

    # ── Helper: read secret from .secrets.d/ (multiline) or .secrets (single-line)
    get_secret() {
      local key="$1"
      # Prefer .secrets.d/ (multiline-safe)
      if [ -f "$SECRETS_D/$key" ]; then
        cat "$SECRETS_D/$key"
        return
      fi
      # Fallback to .secrets KEY=VALUE
      if [ -f "$SECRETS" ]; then
        grep "^''${key}=" "$SECRETS" | head -1 | cut -d'=' -f2-
      fi
    }

    # ── Write keys ──────────────────────────────────────────────────────
    write_key() {
      local name="$1"
      local secret_key="$2"
      local path="$SSH_DIR/$name"
      local val
      val=$(get_secret "$secret_key")
      if [ -z "$val" ]; then
        echo "$SK_LOG WARNING: $secret_key not found — skipping $name"
        return
      fi
      local current=""
      [ -f "$path" ] && current=$(cat "$path")
      if [ "$current" != "$val" ]; then
        printf '%s' "$val" > "$path"
        chmod 600 "$path"
        echo "$SK_LOG Wrote $path ($(printf '%s' "$val" | wc -c) bytes)"
      else
        echo "$SK_LOG $path unchanged"
      fi
    }

    write_key "vault_id_rsa"          "VAULT_ID_RSA"
    write_key "vault_id_rsa.pub"      "VAULT_ID_RSA_PUB"
    write_key "google_compute_engine" "GCP_COMPUTE_ENGINE"
    write_key "google_compute_engine.pub" "GCP_COMPUTE_ENGINE_PUB"

    # fix .pub permissions (644 not 600)
    for pub in "$SSH_DIR"/*.pub; do
      [ -f "$pub" ] && chmod 644 "$pub"
    done

    # ── Write SSH config (WireGuard IPs — all traffic via mesh) ──────────
    CONFIG="$SSH_DIR/config"
    NEW_CONFIG='# Auto-generated by ssh-keys.nix — DO NOT EDIT MANUALLY
# All hosts use WireGuard IPs (mesh always up on oci-apps)

# OCI Micro 1 - Mail Server
Host oci-mail
    HostName 10.0.0.3
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# OCI Micro 2 - Analytics
Host oci-analytics
    HostName 10.0.0.4
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# OCI A1 Flex Paid - Apps 2
Host oci-apps-2
    HostName 10.0.0.7
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# GCP Proxy (WireGuard hub — use public IP to avoid loopback)
Host gcp-proxy
    HostName 35.226.147.64
    User diego
    IdentityFile ~/.ssh/google_compute_engine
    IdentitiesOnly yes

# GCP T4 Spot - Ollama
Host gcp-t4
    HostName 10.0.0.8
    User diego
    IdentityFile ~/.ssh/google_compute_engine
    IdentitiesOnly yes

Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

Host *
    StrictHostKeyChecking accept-new
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h-%p
    ControlPersist 600
'

    current_config=""
    [ -f "$CONFIG" ] && current_config=$(cat "$CONFIG")
    if [ "$current_config" != "$NEW_CONFIG" ]; then
      printf '%s' "$NEW_CONFIG" > "$CONFIG"
      chmod 600 "$CONFIG"
      echo "$SK_LOG Wrote $CONFIG"
    else
      echo "$SK_LOG $CONFIG unchanged"
    fi
  '';
}
