# SSH key deployment — reads from .secrets.d/ (multiline) or .secrets (single-line)
# and writes to ~/.ssh/ so containers mounting ~/.ssh can SSH out via WireGuard.
{ lib, ... }:

{
  home.activation.sshKeys = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    SK_LOG="[ssh-keys]"
    SECRETS="$HOME/.config/home-manager/.secrets"
    SECRETS_D="$HOME/.config/home-manager/.secrets.d"
    SSH_DIR="$HOME/.ssh"
    SOCKETS="$SSH_DIR/sockets"

    if [ ! -d "$SECRETS_D" ]; then
      echo "$SK_LOG No .secrets.d/ — skipping"
      exit 0
    fi

    mkdir -p "$SSH_DIR" "$SOCKETS"
    chmod 700 "$SSH_DIR"

    # ── Deploy keys: .secrets.d/KEY → ~/.ssh/name ──
    deploy_key() {
      local src="$SECRETS_D/$1"
      local dst="$SSH_DIR/$2"
      local perm="$3"
      if [ ! -f "$src" ]; then
        echo "$SK_LOG WARNING: $1 not found — skipping"
        return
      fi
      cp "$src" "$dst"
      chmod "$perm" "$dst"
      echo "$SK_LOG $dst ($(wc -c < "$dst") bytes)"
    }

    deploy_key VAULT_ID_RSA          vault_id_rsa          600
    deploy_key VAULT_ID_RSA_PUB      vault_id_rsa.pub      644
    deploy_key GCP_COMPUTE_ENGINE    google_compute_engine  600
    deploy_key GCP_COMPUTE_ENGINE_PUB google_compute_engine.pub 644

    # ── Write SSH config (WireGuard IPs — all traffic via mesh) ──────────
    CONFIG="$SSH_DIR/config"
    NEW_CONFIG='# Auto-generated by ssh-keys.nix — DO NOT EDIT MANUALLY
# All hosts use WireGuard IPs (mesh always up on oci-apps)

# OCI Micro 1 - Mail Server
Host oci-mail
    HostName 10.0.0.3
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# OCI Micro 2 - Analytics
Host oci-analytics
    HostName 10.0.0.4
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# OCI A1 Flex Paid - Apps 2
Host oci-apps-2
    HostName 10.0.0.7
    User ubuntu
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

# GCP Proxy (WireGuard hub — use public IP to avoid loopback)
Host gcp-proxy
    HostName 35.226.147.64
    User diego
    IdentityFile ~/.ssh/google_compute_engine
    IdentitiesOnly yes

# GCP T4 Spot - Ollama
Host gcp-t4
    HostName 10.0.0.8
    User diego
    IdentityFile ~/.ssh/google_compute_engine
    IdentitiesOnly yes

Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

Host *
    StrictHostKeyChecking accept-new
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h-%p
    ControlPersist 600
'

    current_config=""
    [ -f "$CONFIG" ] && current_config=$(cat "$CONFIG")
    if [ "$current_config" != "$NEW_CONFIG" ]; then
      printf '%s' "$NEW_CONFIG" > "$CONFIG"
      chmod 600 "$CONFIG"
      echo "$SK_LOG Wrote $CONFIG"
    else
      echo "$SK_LOG $CONFIG unchanged"
    fi
  '';
}
