# SSH key deployment — reads from .secrets.d/ and writes to ~/.ssh/.
#
# Also writes SSH keys + config to /opt/ssh-keys/<container>/ on the host.
# Docker compose bind-mounts these directories into containers (:ro).
# Keys persist across container recreation (unlike the old docker cp approach).
#
# Container SSH targets are derived from each per-service a_solutions/*/build.json
# top-level `ssh` field, aggregated by cloud-data-config-consolidated.ts into
# _cloud-data-consolidated.json[._home_manager.vms.<alias>.ssh_containers].
# Per-VM slice also lives in 1_cloud-configs/dist/build-vm-<alias>.json.ssh_containers.
# This module reads from the consolidated JSON (no standalone duplicate file).
{ vmName }:
{ lib, ... }:

let
  # 2026-04-27 migrated: cloud-data-home-manager.json → _cloud-data-consolidated.json[._home_manager.{ssh_config,vms}]
  consolidated = builtins.fromJSON (builtins.readFile ../_cloud-data-consolidated.json);
  cloudData = {
    ssh_config = consolidated._home_manager.ssh_config or [];
  };
  vmHm = consolidated._home_manager.vms.${vmName} or {};
  sshContainers = vmHm.ssh_containers or [];
  containerTargets = lib.concatStringsSep " " (map (c:
    "${c.name}:${toString c.uid}:${c.ssh_dir}:${lib.concatStringsSep "," c.keys}"
  ) sshContainers);
in
{
  home.activation.sshKeys = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    (
    trap 'echo "[ssh-keys] FAILED at line $LINENO (''${FUNCNAME[0]:-main}): $BASH_COMMAND" >&2' ERR
    SK_LOG="[ssh-keys]"
    SECRETS="$HOME/.config/home-manager/.secrets"
    SECRETS_D="$HOME/.config/home-manager/.secrets.d"
    SSH_DIR="$HOME/.ssh"
    SOCKETS="$SSH_DIR/sockets"
    SUDO=""
    if command -v sudo >/dev/null 2>&1; then
      SUDO="sudo"
    elif [ -x /usr/bin/sudo ]; then
      SUDO="/usr/bin/sudo"
    fi

    if [ ! -d "$SECRETS_D" ]; then
      echo "$SK_LOG No .secrets.d/ — skipping"
      exit 0
    fi

    mkdir -p "$SSH_DIR" "$SOCKETS"
    chmod 700 "$SSH_DIR"

    # ── Deploy keys: .secrets.d/KEY → ~/.ssh/name ──
    deploy_key() {
      local src="$SECRETS_D/$1"
      local dst="$SSH_DIR/$2"
      local perm="$3"
      if [ ! -f "$src" ]; then
        echo "$SK_LOG WARNING: $1 not found — skipping"
        return
      fi
      # Remove stale directory if dst exists as a dir (leftover from old deploys)
      if [ -d "$dst" ]; then
        echo "$SK_LOG WARNING: $dst is a directory — removing stale leftover"
        rm -rf "$dst"
      fi
      cp "$src" "$dst"
      chmod "$perm" "$dst"
      echo "$SK_LOG $dst ($(wc -c < "$dst") bytes)"
    }

    deploy_key VAULT_ID_RSA          vault_id_rsa          600
    deploy_key VAULT_ID_RSA_PUB      vault_id_rsa.pub      644
    deploy_key GCP_COMPUTE_ENGINE    google_compute_engine  600
    deploy_key GCP_COMPUTE_ENGINE_PUB google_compute_engine.pub 644

    # ── Write SSH config from cloud-data ──────────────────────────────────
    CONFIG="$SSH_DIR/config"
    NEW_CONFIG='# Auto-generated by security-ssh-keys.nix from cloud-data — DO NOT EDIT
${lib.concatMapStrings (e: ''
Host ${e.host}
    HostName ${e.hostname}
    User ${e.user}
    IdentityFile ${e.identity_file}
    IdentitiesOnly yes
${lib.optionalString ((e.port or 22) != 22) "    Port ${toString e.port}\n"}
'') (builtins.filter (e: e.hostname != "TBD" && e.hostname != null) cloudData.ssh_config)}Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/vault_id_rsa
    IdentitiesOnly yes

Host *
    StrictHostKeyChecking accept-new
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h-%p
    ControlPersist 600
'

    current_config=""
    [ -f "$CONFIG" ] && current_config=$(cat "$CONFIG")
    if [ "$current_config" != "$NEW_CONFIG" ]; then
      printf '%s' "$NEW_CONFIG" > "$CONFIG"
      chmod 600 "$CONFIG"
      echo "$SK_LOG Wrote $CONFIG"
    else
      echo "$SK_LOG $CONFIG unchanged"
    fi

    # ── Deploy SSH keys to /opt/ssh-keys/<container>/ (bind-mounted by compose) ──
    CONTAINER_SSH_TARGETS="${containerTargets}"
    HOST_SSH_BASE="/opt/ssh-keys"

    # Container SSH config: same hosts but no ControlMaster (read-only mount)
    CONTAINER_CONFIG=$(printf '%s' "$NEW_CONFIG" | grep -v 'ControlMaster\|ControlPath\|ControlPersist')

    echo "$SK_LOG ── Container SSH key deployment (/opt/ssh-keys/) ──"

    for entry in $CONTAINER_SSH_TARGETS; do
      CNAME="''${entry%%:*}"
      rest="''${entry#*:}"
      CUID="''${rest%%:*}"
      rest="''${rest#*:}"
      CSSH_DIR="''${rest%%:*}"
      KEYS="''${rest#*:}"

      TARGET_DIR="$HOST_SSH_BASE/$CNAME"

      $SUDO mkdir -p "$TARGET_DIR"

      # Write container SSH config (no ControlMaster)
      printf '%s' "$CONTAINER_CONFIG" | $SUDO tee "$TARGET_DIR/config" >/dev/null

      # Copy each key
      IFS=',' read -ra KEY_LIST <<< "$KEYS"
      for keyfile in "''${KEY_LIST[@]}"; do
        local_key="$SSH_DIR/$keyfile"
        if [ ! -f "$local_key" ]; then
          echo "$SK_LOG [$CNAME] $keyfile not found locally — skipping"
          continue
        fi
        $SUDO cp "$local_key" "$TARGET_DIR/$keyfile"
      done

      # Set ownership and permissions
      $SUDO chown -R "$CUID:$CUID" "$TARGET_DIR"
      $SUDO chmod 700 "$TARGET_DIR"
      $SUDO chmod 600 "$TARGET_DIR/config"
      for keyfile in "''${KEY_LIST[@]}"; do
        [ ! -f "$TARGET_DIR/$keyfile" ] && continue
        if echo "$keyfile" | grep -q '\.pub$'; then
          $SUDO chmod 644 "$TARGET_DIR/$keyfile"
        else
          $SUDO chmod 600 "$TARGET_DIR/$keyfile"
        fi
      done

      echo "$SK_LOG [$CNAME] Keys deployed to $TARGET_DIR (uid=$CUID)"
    done

    echo "$SK_LOG ── Container SSH deployment complete ──"

    if [ "''${DEPLOY_FAILED:-}" = true ]; then
      echo "$SK_LOG FATAL: Container SSH key deployment failed — aborting activation" >&2
      exit 1
    fi
    )
  '';
}
