[Interface]
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT; iptables -I FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o wg0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.0.0.0/24 -o wg0 -j MASQUERADE
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = <REDACTED>

[Peer]
# OCI Flex (oci-p-flex_1)
PublicKey = uUtpR3frleNgOQvQcPvC0y5vWWtmRpJnIvWrqx9gYQU=
AllowedIPs = 10.0.0.2/32
Endpoint = 144.24.196.72:51820
PersistentKeepalive = 25

[Peer]
# OCI Micro1 (oci-f-micro_1)
PublicKey = 1E7ofexq/gHZXnLNXFvpm9O6qtZDJD40IfSpHZ7Pezc=
AllowedIPs = 10.0.0.3/32
Endpoint = 130.110.251.193:51820
PersistentKeepalive = 25

[Peer]
# OCI Micro2 (oci-f-micro_2)
PublicKey = DJTyVo/SYUUDI45brx15mcWxdzXPlIL7+/Y3Cb8AuTA=
AllowedIPs = 10.0.0.4/32
Endpoint = 129.151.228.66:51820
PersistentKeepalive = 25

[Peer]
# Mobile
PublicKey = 9nL3UbbPUVeU1LeMOjFn1e7u5UQnQGClQY5YsKxmpwo=
AllowedIPs = 10.0.0.5/32
