// derive-dagu-repo-map.ts
//
// Stamps the ops_git-sync DAG's REPO_MAP from the ONE place that already
// declares local_dir -> github_repo: cloud-cgc-mcp's build.json.
//
// Why this exists: ops_git-sync.yaml is the SINGLE writer of the octocode_repos
// volume that cloud-cgc-mcp indexes, and its REPO_MAP was a HAND-COPIED
// duplicate of .runtime.octocode.repo_map. Its own comment claimed "Data-driven:
// REPO_MAP mirrors cloud-cgc-mcp build.json ... Never hardcode elsewhere" while
// being exactly that hardcode. It then went stale across the cloud-* rename:
// `cloud:cloud` cloned the 110 KB symlink INDEX repo instead of the 454 MB
// cloud-infra codebase, `unix:unix`/`tools:tools` survived only on GitHub's
// rename redirect, and front-data was missing outright. The volume silently
// drifted from what index_repos expects. A copy that must be kept in sync by
// hand is the bug; deleting the copy is the fix.
//
// Input (read-only, single source of truth):
//   - a_solutions/user-ai_cloud-cgc-mcp/build.json  <- .runtime.octocode.repo_map
//
// Output (line rewritten in place, both source and its committed dist mirror):
//   - a_solutions/infra-obs_dagu/src/dags/ops_git-sync.yaml
//   - a_solutions/infra-obs_dagu/dist/assets/dags/ops_git-sync.yaml
//
// Per fire-rule 6: adding a repo to build.json.repo_map puts it in the DAG on
// the next build. Never edit the REPO_MAP line by hand.

import * as fs from 'node:fs';
import * as path from 'node:path';

const ENGINE_DIR  = import.meta.dirname!;
const CONFIGS_DIR = path.resolve(ENGINE_DIR, '..', '..');
const CLOUD_ROOT  = process.env.CLOUD_ROOT ?? path.resolve(CONFIGS_DIR, '..');
const SOLUTIONS   = path.join(CLOUD_ROOT, 'a_solutions');

const SRC_BUILD_JSON = path.join(SOLUTIONS, 'user-ai_cloud-cgc-mcp', 'build.json');
const TARGETS = [
  path.join(SOLUTIONS, 'infra-obs_dagu', 'src', 'dags', 'ops_git-sync.yaml'),
  path.join(SOLUTIONS, 'infra-obs_dagu', 'dist', 'assets', 'dags', 'ops_git-sync.yaml'),
];

// The generated line, plus the marker that tells a human to stop editing it.
const MARKER = '  # GENERATED by 1_cloud-configs/src/derive/derive-dagu-repo-map.ts — DO NOT EDIT.';
const SOURCE = '  # Source of truth: a_solutions/user-ai_cloud-cgc-mcp/build.json .runtime.octocode.repo_map';
const REPO_MAP_RE = /^[ \t]*-[ \t]*REPO_MAP:.*$/m;

function main(): void {
  const bj = JSON.parse(fs.readFileSync(SRC_BUILD_JSON, 'utf8'));
  const map: Record<string, string> | undefined = bj?.runtime?.octocode?.repo_map;
  const indexRepos: string[] | undefined = bj?.runtime?.octocode?.index_repos;

  if (!map || Object.keys(map).length === 0) {
    throw new Error(`${SRC_BUILD_JSON}: .runtime.octocode.repo_map is missing or empty`);
  }

  // cloud-cgc-db-update.sh:388 hard-fails the whole indexing job when a repo in
  // index_repos has no /repos/<dir>. That directory only exists if this DAG
  // cloned it, which only happens if repo_map declares it. Catch the mismatch
  // here, at build time, instead of at 04:00 in a failed GHA run.
  const missing = (indexRepos ?? []).filter((r) => !(r in map));
  if (missing.length > 0) {
    throw new Error(
      `index_repos entries absent from repo_map: ${missing.join(', ')} — ` +
      `the git-sync DAG would never clone them and cloud-cgc-db-update.sh would abort`,
    );
  }

  const pairs = Object.entries(map).map(([local, remote]) => `${local}:${remote}`);
  const line = `  - REPO_MAP: ${pairs.join(' ')}`;

  for (const target of TARGETS) {
    if (!fs.existsSync(target)) {
      console.log(`[dagu-repo-map] skip (absent): ${path.relative(CLOUD_ROOT, target)}`);
      continue;
    }
    const before = fs.readFileSync(target, 'utf8');
    if (!REPO_MAP_RE.test(before)) {
      throw new Error(`${target}: no REPO_MAP line to stamp`);
    }

    // Replace the REPO_MAP line and re-assert the two comment lines above it,
    // dropping any previously-stamped pair so re-running stays idempotent.
    const after = before
      .split('\n')
      .filter((l) => l !== MARKER && l !== SOURCE)
      .join('\n')
      .replace(REPO_MAP_RE, `${MARKER}\n${SOURCE}\n${line}`);

    if (after === before) {
      console.log(`[dagu-repo-map] unchanged: ${path.relative(CLOUD_ROOT, target)}`);
      continue;
    }
    fs.writeFileSync(target, after);
    console.log(`[dagu-repo-map] stamped ${pairs.length} repos → ${path.relative(CLOUD_ROOT, target)}`);
  }

  console.log(`[dagu-repo-map] repo_map: ${pairs.join(' ')}`);
}

main();
