// derive-repo-map.ts
//
// ONE source of truth for "which local dir holds which GitHub repo":
// the repo registry at cloud/repos.json. Everything downstream is stamped
// from it, so no two files can disagree again.
//
//   cloud/repos.json  (registry: name -> url)
//        |
//        +-> a_solutions/user-ai_cloud-cgc-pub-mcp/build.json .runtime.octocode.repo_map
//                 |
//                 +-> a_solutions/infra-obs_dagu/{src,dist/assets}/dags/ops_git-sync.yaml  REPO_MAP
//
// Why this exists: all three used to be maintained BY HAND. ops_git-sync.yaml is
// the SINGLE writer of the octocode_repos volume that cloud-cgc-pub-mcp indexes, and
// its copy went stale across the cloud-* rename — `cloud:cloud` cloned the 110 KB
// symlink INDEX repo instead of the 454 MB cloud-infra codebase, `unix`/`tools`
// survived only on GitHub's rename redirect, and front-data was missing outright.
// The volume silently drifted from what index_repos expects. A copy that must be
// kept in sync by hand IS the bug; deleting the copy is the fix.
//
// The registry declares local name == GitHub name for every repo except
// `front` -> diegonmarcos.github.io, which the registry itself already encodes.
// So repo_map is pure derived data with no special cases to hand-maintain.
//
// index_repos stays hand-curated — WHICH repos are worth an octocode/GraphRAG
// pass is a cost judgement, not derivable. But it is validated to be a subset of
// the registry, so a repo that is not declared can never be indexed by accident.
//
// Per fire-rule 6: adding a repo to cloud/repos.json is the only edit needed.

import * as fs from 'node:fs';
import * as path from 'node:path';

const ENGINE_DIR  = import.meta.dirname!;
const CONFIGS_DIR = path.resolve(ENGINE_DIR, '..', '..');
const CLOUD_ROOT  = process.env.CLOUD_ROOT ?? path.resolve(CONFIGS_DIR, '..');
const SOLUTIONS   = path.join(CLOUD_ROOT, 'a_solutions');

const REGISTRY   = path.join(CLOUD_ROOT, 'cloud', 'repos.json');
const BUILD_JSON = path.join(SOLUTIONS, 'user-ai_cloud-cgc-pub-mcp', 'build.json');
const DAG_FILES  = [
  path.join(SOLUTIONS, 'infra-obs_dagu', 'src', 'dags', 'ops_git-sync.yaml'),
  path.join(SOLUTIONS, 'infra-obs_dagu', 'dist', 'assets', 'dags', 'ops_git-sync.yaml'),
];

const MARKER = '  # GENERATED by 1_cloud-configs/src/derive/derive-repo-map.ts — DO NOT EDIT.';
const SOURCE = '  # Source of truth: cloud/repos.json -> cloud-cgc-pub-mcp build.json .runtime.octocode.repo_map';
const REPO_MAP_RE = /^[ \t]*-[ \t]*REPO_MAP:.*$/m;

function ghName(url: string): string {
  return url.replace(/^.*[:/]diegonmarcos\//, '').replace(/\.git$/, '');
}

function main(): void {
  // The registry lives in the `cloud` submodule. A CI checkout without
  // submodules would silently derive an EMPTY map and wipe every consumer,
  // so treat absence as fatal rather than as "no repos".
  if (!fs.existsSync(REGISTRY)) {
    throw new Error(
      `${REGISTRY} not found — the 'cloud' submodule is not checked out. ` +
      `Refusing to stamp an empty repo_map. Run: git submodule update --init cloud`,
    );
  }

  const registry = JSON.parse(fs.readFileSync(REGISTRY, 'utf8'));
  const declared: Array<{ name: string; url: string }> = registry.repos ?? [];
  if (declared.length === 0) throw new Error(`${REGISTRY}: no repos declared`);

  const bj = JSON.parse(fs.readFileSync(BUILD_JSON, 'utf8'));
  const oct = bj?.runtime?.octocode;
  if (!oct) throw new Error(`${BUILD_JSON}: .runtime.octocode missing`);

  // Repos that must never land in the shared /repos volume. cloud-cgc-pub-mcp mounts
  // that volume and indexes everything in it, so a credential store there would
  // end up embedded in the GraphRAG DB. Declared as data + reason, not inferred.
  const exclude: Record<string, string> = oct.sync_exclude ?? {};

  const byName = new Map<string, string>();
  for (const r of declared) {
    if (r?.name && r?.url) byName.set(r.name, ghName(r.url));
  }

  // repo_map is SCOPED to index_repos, not to the whole registry. The DAG clones
  // every entry into the shared volume on a */15 schedule, so mapping all 12
  // declared repos would drag front-assets-cdn (1.4 GB of CDN assets) and the
  // LFS/game repos onto oci-apps for nothing. index_repos is the one curated
  // cost decision; the local->github mapping under it is pure derived data.
  const indexRepos: string[] = oct.index_repos ?? [];

  // A repo that is not declared in the registry can never be indexed. Without
  // this, a typo or an invented name reaches cloud-cgc-db-update.sh:388, which
  // aborts the whole indexing job mid-run at 04:00.
  const undeclared = indexRepos.filter((r) => !byName.has(r));
  if (undeclared.length > 0) {
    throw new Error(
      `index_repos entries not declared in cloud/repos.json: ${undeclared.join(', ')} — ` +
      `declare them in the registry first, or they will never be cloned and ` +
      `cloud-cgc-db-update.sh will abort at :388`,
    );
  }

  // Hard stop: the shared volume is mounted and indexed by cloud-cgc-pub-mcp, so a
  // credential store landing there ends up embedded in the GraphRAG DB.
  const forbidden = indexRepos.filter((r) => r in exclude);
  if (forbidden.length > 0) {
    throw new Error(
      `index_repos contains repos excluded from the shared volume: ` +
      forbidden.map((r) => `${r} (${exclude[r]})`).join(', '),
    );
  }

  const map: Record<string, string> = {};
  for (const name of indexRepos) map[name] = byName.get(name)!;

  const skipped = declared
    .map((r) => r?.name)
    .filter((n) => n && !(n in map))
    .map((n) => (n in exclude ? `${n} (${exclude[n]})` : `${n} (not in index_repos)`));

  // 1) stamp build.json
  const beforeMap = JSON.stringify(oct.repo_map ?? {});
  if (JSON.stringify(map) !== beforeMap) {
    oct.repo_map = map;
    fs.writeFileSync(BUILD_JSON, JSON.stringify(bj, null, 2) + '\n');
    console.log(`[repo-map] build.json repo_map <- registry (${Object.keys(map).length} repos)`);
  } else {
    console.log('[repo-map] build.json unchanged');
  }

  // 2) stamp the DAG(s)
  const line = `  - REPO_MAP: ${Object.entries(map).map(([l, g]) => `${l}:${g}`).join(' ')}`;
  for (const target of DAG_FILES) {
    if (!fs.existsSync(target)) {
      console.log(`[repo-map] skip (absent): ${path.relative(CLOUD_ROOT, target)}`);
      continue;
    }
    const before = fs.readFileSync(target, 'utf8');
    if (!REPO_MAP_RE.test(before)) throw new Error(`${target}: no REPO_MAP line to stamp`);

    // Drop any previously-stamped comment pair first so re-runs stay idempotent.
    const after = before
      .split('\n')
      .filter((l) => l !== MARKER && l !== SOURCE && !l.startsWith('  # GENERATED by 1_cloud-configs/src/derive/derive-dagu-repo-map.ts'))
      .join('\n')
      .replace(REPO_MAP_RE, `${MARKER}\n${SOURCE}\n${line}`);

    if (after === before) { console.log(`[repo-map] unchanged: ${path.relative(CLOUD_ROOT, target)}`); continue; }
    fs.writeFileSync(target, after);
    console.log(`[repo-map] stamped → ${path.relative(CLOUD_ROOT, target)}`);
  }

  if (skipped.length) console.log(`[repo-map] excluded from /repos: ${skipped.join(', ')}`);
  console.log(`[repo-map] indexed subset: ${indexRepos.join(' ')}`);
}

main();
