#!/bin/sh
set -e
CLOUD_ROOT="${CLOUD_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}"
. "$CLOUD_ROOT/1_workflows/src/scripts/cloud-ship-lib.sh"

# Generate GHA deploy workflows from build.json + templates
cmd_workflow() {
    log "Generating GHA workflows from build.json + templates..."

    WF_SRC="$CLOUD_ROOT/1_workflows/src"
    WF_DIST="$CLOUD_ROOT/1_workflows/dist"
    GH_DIR="$CLOUD_ROOT/.github/workflows"
    mkdir -p "$WF_DIST"

    # ── Copy static workflows (ship.yml + health + terraform + etc.) ──
    # ship.yml uses dynamic VM matrix from cloud-data-gha-config.json at runtime
    # — no per-VM template generation needed
    rm -f "$WF_DIST"/*.yml
    for f in "$WF_SRC"/cicd/*.yml; do
        [ -f "$f" ] || continue
        cp "$f" "$WF_DIST/"
    done
    generated=$(ls "$WF_DIST"/*.yml 2>/dev/null | wc -l)
    log "  Static workflows copied ($generated files)"

    # ── Regenerate cloud-data-gha-config.json (source of truth for ship.yml detect job) ──
    GHA_CONFIG="$CLOUD_ROOT/I_cloud-data/cloud-data-gha-config.json"
    {
        log "Generating cloud-data-gha-config.json via tsx..."
        C3_SRC="$CLOUD_ROOT/a_solutions/bc-obs_c3-infra-api/src"
        TOPO_FILE="$CLOUD_ROOT/I_cloud-data/cloud-data-topology.json"

        if [ -f "$TOPO_FILE" ] && [ -f "$C3_SRC/gen-gha-config.ts" ]; then
            CONFIG_JSON_PATH="$TOPO_FILE" GIT_BASE="${GIT_BASE:-$(dirname "$CLOUD_ROOT")}" \
            tsx "$C3_SRC/gen-gha-config.ts" > "$GHA_CONFIG" 2>/dev/null

            if [ -s "$GHA_CONFIG" ]; then
                log "  Generated gha-config locally ($(jq '.services | length' "$GHA_CONFIG") services)"
            else
                rm -f "$GHA_CONFIG"
                log_error "tsx generation produced empty output"
            fi
        fi
    }
    [ -f "$GHA_CONFIG" ] && log "  cloud-data-gha-config.json: $(jq '.services | length' "$GHA_CONFIG") services, $(jq '.vms | length' "$GHA_CONFIG") VMs"

    # ── Inject read-only header into ALL dist/ files ──
    inject_header() {
        _file="$1"
        [ -f "$_file" ] || return 0
        # Skip if already has header
        head -1 "$_file" | grep -q 'DO NOT EDIT' && return 0
        # Skip binary/non-text files
        file "$_file" 2>/dev/null | grep -q 'text' || return 0

        # Resolve source path relative to dist/
        _rel="${_file#$WF_DIST/}"
        _src_path="1_workflows/src/$_rel"

        # Detect comment style from extension/shebang
        case "$_file" in
            *.yml|*.yaml) _cs="#" ;;
            *.nix)        _cs="#" ;;
            *.json)
                # JSON: inject as top-level "_DO_NOT_EDIT" key
                grep -q '_DO_NOT_EDIT' "$_file" && return 0
                _msg="DO NOT EDIT — read-only generated output | engine: cloud/build.sh workflow | source: cloud/${_src_path}"
                _tmp=$(jq --arg m "$_msg" '{"_DO_NOT_EDIT": $m} + .' "$_file") && printf '%s\n' "$_tmp" > "$_file"
                return 0
                ;;
            *)
                if head -1 "$_file" | grep -q '^#!'; then
                    _cs="#"  # shell scripts
                else
                    _cs="#"  # default
                fi
                ;;
        esac

        _header="${_cs} ┌──────────────────────────────────────────────────────────────┐
${_cs} │  DO NOT EDIT THIS FILE!                                      │
${_cs} │                                                              │
${_cs} │  This file is READ-ONLY generated output.                    │
${_cs} │  It is declaratively managed by the workflow engine.         │
${_cs} │                                                              │
${_cs} │  Engine: cloud/build.sh workflow                             │
${_cs} │  Source: cloud/${_src_path}                                  │
${_cs} │                                                              │
${_cs} │  To change: edit the source, run build.sh workflow, commit.  │
${_cs} └──────────────────────────────────────────────────────────────┘
"
        # Preserve shebang line if present
        if head -1 "$_file" | grep -q '^#!'; then
            _shebang=$(head -1 "$_file")
            _body=$(tail -n +2 "$_file")
            printf '%s\n%s\n%s\n' "$_shebang" "$_header" "$_body" > "$_file.tmp"
        else
            printf '%s\n' "$_header" | cat - "$_file" > "$_file.tmp"
        fi
        mv "$_file.tmp" "$_file"
    }

    # ── Stage ALL src/ → dist/ ──
    # scripts
    if [ -d "$WF_SRC/scripts" ]; then
        mkdir -p "$WF_DIST/scripts"
        cp "$WF_SRC/scripts/"* "$WF_DIST/scripts/"
        chmod +x "$WF_DIST/scripts/"*.sh 2>/dev/null || true
    fi
    # hooks
    if [ -d "$WF_SRC/hooks" ]; then
        mkdir -p "$WF_DIST/hooks"
        cp "$WF_SRC/hooks/"* "$WF_DIST/hooks/"
        chmod +x "$WF_DIST/hooks/"* 2>/dev/null || true
    fi
    # actions
    if [ -d "$WF_SRC/actions" ]; then
        rm -rf "$WF_DIST/actions"
        cp -r "$WF_SRC/actions" "$WF_DIST/actions"
    fi
    # deps
    if [ -d "$WF_SRC/deps" ]; then
        mkdir -p "$WF_DIST/deps"
        cp "$WF_SRC/deps/flake.nix" "$WF_DIST/deps/flake.nix"
        [ -f "$WF_SRC/deps/flake.lock" ] && cp "$WF_SRC/deps/flake.lock" "$WF_DIST/deps/flake.lock"
    fi
    # modules (gitmodules)
    if [ -f "$WF_SRC/modules/gitmodules" ]; then
        mkdir -p "$WF_DIST/modules"
        cp "$WF_SRC/modules/gitmodules" "$WF_DIST/modules/gitmodules"
    fi
    # gitconfig
    if [ -f "$WF_SRC/gitconfig" ]; then
        cp "$WF_SRC/gitconfig" "$WF_DIST/gitconfig"
    fi
    log "  All src/ staged to dist/"

    # ── Inject read-only headers into ALL dist/ files ──
    find "$WF_DIST" -type f | while read -r _f; do
        inject_header "$_f"
    done
    log "  Headers injected"

    # ── Deploy dist/ → targets ──

    # workflows: dist/*.yml → .github/workflows/
    find "$GH_DIR" -maxdepth 1 -name '*.yml' -type f -exec rm -f {} +
    cp "$WF_DIST"/*.yml "$GH_DIR/"

    # scripts: dist/scripts/ → .github/workflows/scripts (symlink)
    rm -rf "$GH_DIR/scripts"
    ln -s "../../1_workflows/dist/scripts" "$GH_DIR/scripts"

    # hooks: dist/hooks/ → via .gitconfig hooksPath (no copy needed, path points to dist/)
    log "  Git hooks deployed"

    # actions: dist/actions/ → .github/actions/
    if [ -d "$WF_DIST/actions" ]; then
        rm -rf "$CLOUD_ROOT/.github/actions"
        cp -r "$WF_DIST/actions" "$CLOUD_ROOT/.github/actions"
        log "  Actions deployed"
    fi

    # deps flake: dist/deps/ → .github/
    if [ -d "$WF_DIST/deps" ]; then
        cp "$WF_DIST/deps/flake.nix" "$CLOUD_ROOT/.github/flake.nix"
        [ -f "$WF_DIST/deps/flake.lock" ] && cp "$WF_DIST/deps/flake.lock" "$CLOUD_ROOT/.github/flake.lock"
        log "  Deps flake deployed"
    fi

    # gitmodules: dist/modules/gitmodules → .gitmodules
    if [ -f "$WF_DIST/modules/gitmodules" ]; then
        if [ -f "$CLOUD_ROOT/.gitmodules" ]; then
            if ! diff -q "$WF_DIST/modules/gitmodules" "$CLOUD_ROOT/.gitmodules" >/dev/null 2>&1; then
                log "  WARNING: .gitmodules diverged from source — overwriting"
            fi
        fi
        cp "$WF_DIST/modules/gitmodules" "$CLOUD_ROOT/.gitmodules"
        log "  Submodules config deployed"
    fi

    # gitconfig: dist/gitconfig → .gitconfig
    if [ -f "$WF_DIST/gitconfig" ]; then
        cp "$WF_DIST/gitconfig" "$CLOUD_ROOT/.gitconfig"
        if ! git -C "$CLOUD_ROOT" config --local --get include.path 2>/dev/null | grep -q '.gitconfig'; then
            git -C "$CLOUD_ROOT" config --local include.path ../.gitconfig
        fi
        log "  Repo gitconfig deployed"
    fi

    log "Deployed $generated workflow(s) → 1_workflows/dist/ → .github/workflows/"
}

cmd_workflow "$@"
