[Interface]
PrivateKey = <REDACTED>
Address = 10.0.0.4/24
ListenPort = 51820

[Peer]
# GCP Hub
PublicKey = GGZzgZDrOwvw1Th8iKWKeOOBgh+UvAjnmdi1iE9E1Hk=
AllowedIPs = 10.0.0.0/24
Endpoint = 35.226.147.64:51820
PersistentKeepalive = 25
